words:
  - avenir
  - drei
  - glsl
  - grayscale
  - Hdot
  - Ndot
  - reekystive
  - Schlick
flagWords:
  - blacklist -> blocklist
  - whitelist -> allowlist
suggestWords:
  - colour -> color
ignorePaths:
  - cspell.config.yaml
